### ISSUE TITLE
Videos do not load

### ISSUE THREAD

**Issue by nicxvan** [linuxserver/docker-kodi-headless#107]
When starting there is no videos to view, I've got the videos mounted but it just spins and I see no way to add sources.

Here is my docker-compose

```
kodi:
    image: linuxserver/kodi-headless
    restart: unless-stopped
    container_name: kodi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/kodi:/config
      - /mnt/video:/media/video
      - /mnt/music:/media/music
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 7888:8080
      - 9090:9090
      - 9777:9777/udp
```
