### ISSUE TITLE
Scanning for video info took 00:00

### ISSUE THREAD

**Issue by raupie** [linuxserver/docker-kodi-headless#109]
Using a FreeNAS setup running RancherOS in a Virtual Machine. 

I am using docker-compose.yml to get a docker stack up and running with mariadb + phpmyadmin container running. 
```
version: "2"
services:
  kodi:
    image: linuxserver/kodi-headless
    container_name: kodi-headless
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - backend
    environment:
      - PUID=10001
      - PGID=10001
      - TZ=America/New_York
    ports:
      - 9005:8080
      - 9006:9090
      - 9777:9777/udp
    volumes:
      - /mnt/projects/kodi-headless/kodi:/config/.kodi
      - /mnt/nfs/movies:/mnt/movies
      - /mnt/nfs/series:/mnt/series
```

As you can see I have the movies and series added as a volume mount. I did have this setup for trying to use it over my nfs shares in the sources.xml file. Instead I have added the volumes and updated sources.xml to reflect the correct path to the media. 

When I try to update the library over curl I get a 
```
2020-01-18 00:51:23.550 T:140322873005824  NOTICE: VideoInfoScanner: Starting scan ..
2020-01-18 00:51:23.550 T:140322873005824  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
```

I've enabled debug but I don't get any more info in kodi.log regarding why the scan stops so quickly.

I'm trying to do a full scan on an empty database. I can confirm that the MyVideos116 database gets created during the build process. 

I assume that the default scrapers will be used which are defined in the guisettings.xml. 

I'm at a loss on what to do next.
