### ISSUE TITLE
Raspberry 4b 64 bit Rasbian Buster aarch64 image status restarting

### ISSUE THREAD

**Issue by Mahelita** [linuxserver/docker-kodi-headless#126]
### Issue:
- kodi not reachable on web interface using http://ip.of.pi.4b:8080
- docker-compose ps shows normal status (port mappings) for couple of seconds then shows restarting forever

### Host OS:
Raspbian Buster 64 bit

### docker-compose.yml:
```
version: "2.1"
services:
  kodi:
    image: lsioarmhf/kodi-headless-aarch64
    container_name: kodi-headless
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Berlin
    ports:
      - 9005:8080
      - 9006:9090
      - 9777:9777/udp
    volumes:
      - /home/pi/kodi:/config/.kodi
#      - /movies:/mnt/movies
#      - /music:/mnt/music
    restart: unless-stopped
```
### Docker log output, docker log <container-name>:
Not getting any logs except on a single occasion:
kodi-headless exited with code 159
Same code is show in status of ```docker-compose ps``` when manually stopping using ```docker-compose stop```
### Mention if you're using symlinks on any of the volume mounts:
Not using symlinks
