### ISSUE TITLE
Can't get UPNP/DLNA to work?

### ISSUE THREAD

**Issue by AnderssonPeter** [linuxserver/docker-kodi-headless#79]
Host OS: ubuntu server 18.04.1

advancedsettings.xml
```xml
<advancedsettings>
    <videodatabase>
        <type>mysql</type>
        <host>mariadb</host>
        <port>****</port>
        <user>kodi</user>
        <pass>kodi</pass>
    </videodatabase>
    <videolibrary>
        <importwatchedstate>true</importwatchedstate>
        <importresumepoint>true</importresumepoint>
    </videolibrary>
    <services>
        <devicename>KODI Server</devicename>
        <esallinterfaces>true</esallinterfaces>
        <!-- don't change this value -->
        <escontinuousdelay>25</escontinuousdelay>
        <esenabled>true</esenabled>
        <!-- don't change this value -->
        <esinitialdelay>750</esinitialdelay>
        <esmaxclients>20</esmaxclients>
        <esport>9777</esport>
        <!-- don't change this value -->
        <esportrange>10</esportrange>
        <upnpannounce>true</upnpannounce>
        <upnprenderer>false</upnprenderer>
        <upnpserver>true</upnpserver>
        <webserver>true</webserver>
        <!-- don't change this value -->
        <webserverpassword>kodi</webserverpassword>
        <webserverport>8444</webserverport>
        <!-- don't change this value -->
        <webserverusername>kodi</webserverusername>
        <zeroconf>false</zeroconf>
    </services>
</advancedsettings>
```

Docker-compose.yaml
```yaml
  kodi:
    image: linuxserver/kodi-headless:Krypton
    restart: unless-stopped
    volumes:
      - /home/peter/data/kodi:/config/.kodi
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8444:8444
      - 9090:9090
      - "9777:9777/udp"
      - 1954:1954
      - "1954:1954/udp"
      - "1900:1900/udp"
      - 2869:2869
      - 1084:1084
      - 1308:1308
      - 1131:1131
      - "12374:12374/udp"
    extra_hosts:
      - "mariadb:192.168.0.15"
      - "asgarddomain:192.168.0.158"
    depends_on:
      - mariadb
```

What am I missing?

##  Thanks, team linuxserver.io

**Comment by tobbenb** [comment]
What do you need it for? Kodi headless is to update your library which can be done without upnp or dlna.

**Comment by AnderssonPeter** [comment]
I got a smart TV, would be nice if i could skip the htpc by using DLNA/upnp to stream directly to the tv instead!

**Comment by tobbenb** [comment]
Kodi is not a server.
If you want a server, you can use Plex or Emby.

**Comment by AnderssonPeter** [comment]
If I run kodi on my htpc I can browse and stream from it over the network, so while it's not its intended use it can work as a server!

**Comment by agncr** [comment]
Hey @AnderssonPeter 
if you haven't figured it out yet: 
You could just forward every port via network_mode: host. I got that working with that:


```
---
version: "2"
services:
  kodi-headless:
    image: linuxserver/kodi-headless
    container_name: kodi
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
...
```

It's not like he asked for a new feature... Kodi already offers the DLNA-Server functionality, so why not use it, if it's there and it suits your need.
